yaml cohere: api_key: N5GIeOMsRQFBxsB9EgDRszd5ResA6qarqppgoR7M qdrant: api_key: amv5NQ-sWoljAhoC5jfsruCW8LUSUevrepks03Mj6Nw1oNdTTv7Rcg url: https://2f4df473-89da-4dcd-b4ab-6e59726e8b76.us-east4-0.gcp.cloud.qdrant.io:6333
